apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

resources:
  - ../../base

# En dev usamos 1 réplica para ahorrar recursos
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: backend

  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: envoy