apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: inventory-mgmt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      containers:
        - name: backend
          image: danst21/inventory-backend:704f193c7b7481c1ea9ae778b6b894122f13abd5
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9900
              name: grpc
          # Valores no sensibles del ConfigMap
          envFrom:
            - configMapRef:
                name: backend-config
          # Valores sensibles del Secret creado por ESO desde Vault
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_PASS
            - name: INTERNAL_GRPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: INTERNAL_GRPC_SECRET
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15