apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secret
  namespace: inventory-mgmt
spec:
  refreshInterval: "1h"

  secretStoreRef:
    name: vault-backend
    kind: SecretStore

  target:
    name: backend-secret
    creationPolicy: Owner

  data:
    - secretKey: DB_USER
      remoteRef:
        key: backend
        property: DB_USER

    - secretKey: DB_PASS
      remoteRef:
        key: backend
        property: DB_PASS

    - secretKey: INTERNAL_GRPC_SECRET
      remoteRef:
        key: backend
        property: INTERNAL_GRPC_SECRET