apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: inventory-mgmt
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: grpc
      port: 9000
      targetPort: 9000
      appProtocol: grpc
  type: NodePort