apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast
  namespace: inventory-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hazelcast
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      containers:
        - name: hazelcast
          image: hazelcast/hazelcast:5.3
          ports:
            - containerPort: 5701
          env:
            - name: HZ_CLUSTERNAME
              value: "inventory-cluster"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          readinessProbe:
            httpGet:
              path: /hazelcast/health/ready
              port: 5701
            initialDelaySeconds: 20
            periodSeconds: 10