apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: inventory-mgmt
spec:
  provider:
    vault:
      # URL de Vault dentro del cluster
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "inventory"        # el path que habilitaste con kv-v2
      version: "v2"

      auth:
        # Autenticación con token — simple para dev
        # En producción usa kubernetes auth method
        tokenSecretRef:
          name: vault-token    # el Secret que creamos arriba
          key: token