apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
  namespace: inventory-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      initContainers:
        - name: copy-files
          image: danst21/inventory-backend:latest
          imagePullPolicy: IfNotPresent
          command: ['/bin/sh', '-c', 'cp /app/proto.pb /proto-volume/proto.pb && cp /app/envoy.yaml /envoy-config-volume/envoy.yaml']
          volumeMounts:
            - name: proto-volume
              mountPath: /proto-volume
            - name: envoy-config-volume
              mountPath: /envoy-config-volume
      containers:
        - name: envoy
          image: envoyproxy/envoy:v1.28-latest
          ports:
            - containerPort: 8090
            - containerPort: 9901
          volumeMounts:
            - name: envoy-config-volume
              mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml
            - name: proto-volume
              mountPath: /etc/envoy/proto.pb
              subPath: proto.pb
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: envoy-config-volume
          emptyDir: {}
        - name: proto-volume
          emptyDir: {}