apiVersion: v1
kind: Service
metadata:
  name: envoy
  namespace: inventory-mgmt
spec:
  selector:
    app: envoy
  ports:
    - name: http
      port: 8090
      targetPort: 8090
      nodePort: 30090
    - name: admin
      port: 9901
      targetPort: 9901
  type: NodePort