apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: inventory-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      # Usa el Service Account que tiene permisos en Vault
      serviceAccountName: postgres-sa
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          # Lee del Secret creado por External Secrets Operator
          # El nombre "postgres-secret" es el target.name del ExternalSecret
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - inventory_user
                - -d
                - inventory_db
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc