# ExternalSecret le dice a External Secrets Operator:
# "ve a Vault, lee este path, y crea un Kubernetes Secret con estos valores"
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: inventory-mgmt
spec:
  # Cada cuánto sincroniza con Vault
  refreshInterval: "1h"

  secretStoreRef:
    name: vault-backend      # el SecretStore que creamos
    kind: SecretStore

  # El Kubernetes Secret que se crea automáticamente
  target:
    name: postgres-secret    # nombre del Secret resultante
    creationPolicy: Owner    # ESO es dueño del Secret — lo gestiona él

  # Qué valores jalar de Vault y con qué nombre ponerlos en el Secret
  data:
    - secretKey: POSTGRES_USER      # nombre en el Kubernetes Secret
      remoteRef:
        key: postgres               # path en Vault: inventory/data/postgres
        property: POSTGRES_USER     # campo dentro del secret de Vault

    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres
        property: POSTGRES_PASSWORD

    - secretKey: POSTGRES_DB
      remoteRef:
        key: postgres
        property: POSTGRES_DB