apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: inventory-mgmt
  annotations:
    # Anotación para que Vault sepa que este SA puede usar el rol
    vault.hashicorp.com/role: "inventory-role"