apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: inventory-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      serviceAccountName: keycloak-sa
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0.0
          args: ["start-dev"]
          ports:
            - containerPort: 8080
          env:
            # Valores no sensibles — van directo como value
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://postgres:5432/inventory_db"
          # Valores sensibles — vienen del Secret creado por ESO desde Vault
          envFrom:
            - secretRef:
                name: keycloak-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 10