apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-secret
  namespace: inventory-mgmt
spec:
  refreshInterval: "1h"

  secretStoreRef:
    name: vault-backend
    kind: SecretStore

  target:
    name: keycloak-secret
    creationPolicy: Owner

  data:
    - secretKey: KC_BOOTSTRAP_ADMIN_USERNAME
      remoteRef:
        key: keycloak
        property: KC_BOOTSTRAP_ADMIN_USERNAME

    - secretKey: KC_BOOTSTRAP_ADMIN_PASSWORD
      remoteRef:
        key: keycloak
        property: KC_BOOTSTRAP_ADMIN_PASSWORD

    - secretKey: KC_DB_USERNAME
      remoteRef:
        key: keycloak
        property: KC_DB_USERNAME

    - secretKey: KC_DB_PASSWORD
      remoteRef:
        key: keycloak
        property: KC_DB_PASSWORD